//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Authors = new HashSet<Author>();
            this.ConferenceStaffs = new HashSet<ConferenceStaff>();
            this.Conferences = new HashSet<Conference>();
            this.Messages = new HashSet<Message>();
            this.Messages1 = new HashSet<Message>();
            this.Reviews = new HashSet<Review>();
            this.SpecialSessions = new HashSet<SpecialSession>();
            this.Tasks = new HashSet<Task>();
            this.Tasks1 = new HashSet<Task>();
        }
    
        public int AccountId { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Login { get; set; }
        public string PasswordHash { get; set; }
    
        public virtual ICollection<Author> Authors { get; set; }
        public virtual ICollection<ConferenceStaff> ConferenceStaffs { get; set; }
        public virtual ICollection<Conference> Conferences { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<Message> Messages1 { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual ICollection<SpecialSession> SpecialSessions { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<Task> Tasks1 { get; set; }
    }
}
