//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleAuthor
    {
        public int ArticleAuthorId { get; set; }
        public int ArticleId { get; set; }
        public int AuthorId { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Author Author { get; set; }
    }
}
