//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conference
    {
        public Conference()
        {
            this.AccommodationInfoes = new HashSet<AccommodationInfo>();
            this.ConferenceStaffs = new HashSet<ConferenceStaff>();
            this.ConferenceRooms = new HashSet<ConferenceRoom>();
            this.EmergencyInfoes = new HashSet<EmergencyInfo>();
            this.Events = new HashSet<Event>();
            this.Sessions = new HashSet<Session>();
            this.SpecialSessions = new HashSet<SpecialSession>();
            this.Tasks = new HashSet<Task>();
            this.TravelInfoes = new HashSet<TravelInfo>();
            this.WelcomePacks = new HashSet<WelcomePack>();
            this.Articles = new HashSet<Article>();
        }
    
        public int ConferenceId { get; set; }
        public int ChairId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Place { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual ICollection<AccommodationInfo> AccommodationInfoes { get; set; }
        public virtual Account Account { get; set; }
        public virtual ICollection<ConferenceStaff> ConferenceStaffs { get; set; }
        public virtual ICollection<ConferenceRoom> ConferenceRooms { get; set; }
        public virtual ICollection<EmergencyInfo> EmergencyInfoes { get; set; }
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<Session> Sessions { get; set; }
        public virtual ICollection<SpecialSession> SpecialSessions { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<TravelInfo> TravelInfoes { get; set; }
        public virtual ICollection<WelcomePack> WelcomePacks { get; set; }
        public virtual ICollection<Article> Articles { get; set; }
    }
}
