//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presentation
    {
        public Presentation()
        {
            this.Articles = new HashSet<Article>();
            this.Awards = new HashSet<Award>();
            this.Grades = new HashSet<Grade>();
        }
    
        public int PresentationId { get; set; }
        public int ArticleId { get; set; }
        public int RoomId { get; set; }
        public Nullable<int> SessionId { get; set; }
        public Nullable<int> SpecialSessionId { get; set; }
        public Nullable<int> GradeId { get; set; }
        public Nullable<int> AwardId { get; set; }
    
        public virtual ICollection<Article> Articles { get; set; }
        public virtual Article Article { get; set; }
        public virtual ICollection<Award> Awards { get; set; }
        public virtual Award Award { get; set; }
        public virtual ICollection<Grade> Grades { get; set; }
        public virtual Grade Grade { get; set; }
        public virtual Room Room { get; set; }
        public virtual Session Session { get; set; }
        public virtual SpecialSession SpecialSession { get; set; }
    }
}
