//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public Room()
        {
            this.ConferenceRooms = new HashSet<ConferenceRoom>();
            this.Events = new HashSet<Event>();
            this.Presentations = new HashSet<Presentation>();
            this.Events1 = new HashSet<Event>();
        }
    
        public int RoomId { get; set; }
    
        public virtual ICollection<ConferenceRoom> ConferenceRooms { get; set; }
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<Presentation> Presentations { get; set; }
        public virtual ICollection<Event> Events1 { get; set; }
    }
}
