//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialSession
    {
        public SpecialSession()
        {
            this.Articles = new HashSet<Article>();
            this.Presentations = new HashSet<Presentation>();
        }
    
        public int SpecialSessionId { get; set; }
        public int ConferenceId { get; set; }
        public int ChairId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<Article> Articles { get; set; }
        public virtual Conference Conference { get; set; }
        public virtual ICollection<Presentation> Presentations { get; set; }
    }
}
