//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Submission
    {
        public int SubmissionId { get; set; }
        public int ArticleId { get; set; }
        public byte[] ArticleFile { get; set; }
        public System.DateTime SubmissionDate { get; set; }
    
        public virtual Article Article { get; set; }
    }
}
