//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class WelcomePack
    {
        public WelcomePack()
        {
            this.WelcomePackReceivers = new HashSet<WelcomePackReceiver>();
            this.WelcomePackGifts = new HashSet<WelcomePackGift>();
        }
    
        public int WelcomePackId { get; set; }
        public int ConferenceId { get; set; }
        public string EmployeeName { get; set; }
    
        public virtual Conference Conference { get; set; }
        public virtual ICollection<WelcomePackReceiver> WelcomePackReceivers { get; set; }
        public virtual ICollection<WelcomePackGift> WelcomePackGifts { get; set; }
    }
}
