//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RoleResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RoleResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMS.UI.Properties.RoleResources", typeof(RoleResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AWARDS COORDINATOR.
        /// </summary>
        internal static string AwardsCoordinator {
            get {
                return ResourceManager.GetString("AwardsCoordinator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFERENCE CHAIR.
        /// </summary>
        internal static string ConferenceChair {
            get {
                return ResourceManager.GetString("ConferenceChair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFERENCE MANAGER.
        /// </summary>
        internal static string ConferenceManager {
            get {
                return ResourceManager.GetString("ConferenceManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFERENCE STAFF MANAGER.
        /// </summary>
        internal static string ConferenceStaffManager {
            get {
                return ResourceManager.GetString("ConferenceStaffManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFERENCE STAFF MEMBER.
        /// </summary>
        internal static string ConferenceStaffMember {
            get {
                return ResourceManager.GetString("ConferenceStaffMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDITOR.
        /// </summary>
        internal static string Editor {
            get {
                return ResourceManager.GetString("Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUEST.
        /// </summary>
        internal static string Guest {
            get {
                return ResourceManager.GetString("Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR ADMINISTRATOR.
        /// </summary>
        internal static string HRAdministrator {
            get {
                return ResourceManager.GetString("HRAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFORMATION STAFF.
        /// </summary>
        internal static string InformationStaff {
            get {
                return ResourceManager.GetString("InformationStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRESENTER.
        /// </summary>
        internal static string Presenter {
            get {
                return ResourceManager.GetString("Presenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REVIEWER.
        /// </summary>
        internal static string Reviewer {
            get {
                return ResourceManager.GetString("Reviewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SESSION CHAIR.
        /// </summary>
        internal static string SessionChair {
            get {
                return ResourceManager.GetString("SessionChair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WELCOME PACK STAFF.
        /// </summary>
        internal static string WelcomePackStaff {
            get {
                return ResourceManager.GetString("WelcomePackStaff", resourceCulture);
            }
        }
    }
}
