//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Article()
        {
            this.ArticleAuthors = new HashSet<ArticleAuthor>();
            this.Reviews = new HashSet<Review>();
            this.Submissions = new HashSet<Submission>();
            this.Presentations = new HashSet<Presentation>();
        }
    
        public int ArticleId { get; set; }
        public string Topic { get; set; }
        public Nullable<int> PresentationId { get; set; }
        public Nullable<int> SpecialSessionId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> AcceptanceDate { get; set; }
        public int ConferenceID { get; set; }
    
        public virtual Conference Conference { get; set; }
        public virtual Presentation Presentation { get; set; }
        public virtual SpecialSession SpecialSession { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticleAuthor> ArticleAuthors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Submission> Submissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Presentation> Presentations { get; set; }
    }
}
