//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.API.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cmsEntities : DbContext
    {
        public cmsEntities()
            : base("name=cmsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccommodationInfo> AccommodationInfoes { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<Author> Authors { get; set; }
        public virtual DbSet<Award> Awards { get; set; }
        public virtual DbSet<Conference> Conferences { get; set; }
        public virtual DbSet<ConferenceRoom> ConferenceRooms { get; set; }
        public virtual DbSet<ConferenceStaff> ConferenceStaffs { get; set; }
        public virtual DbSet<EmergencyInfo> EmergencyInfoes { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Presentation> Presentations { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<SpecialSession> SpecialSessions { get; set; }
        public virtual DbSet<Submission> Submissions { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<TravelInfo> TravelInfoes { get; set; }
        public virtual DbSet<WelcomePack> WelcomePacks { get; set; }
        public virtual DbSet<WelcomePackGift> WelcomePackGifts { get; set; }
        public virtual DbSet<WelcomePackReceiver> WelcomePackReceivers { get; set; }
    }
}
