//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int ReviewId { get; set; }
        public int ArticleId { get; set; }
        public int ReviewerId { get; set; }
        public System.DateTime ReviewDate { get; set; }
        public decimal Grade { get; set; }
        public string Title { get; set; }
        public string Comment { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Article Article { get; set; }
    }
}
