//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WelcomePackGift
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WelcomePackGift()
        {
            this.WelcomePackReceivers = new HashSet<WelcomePackReceiver>();
        }
    
        public int WelcomePackGiftId { get; set; }
        public int WelcomePackId { get; set; }
        public string Name { get; set; }
        public int TypeID { get; set; }
    
        public virtual WelcomePack WelcomePack { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WelcomePackReceiver> WelcomePackReceivers { get; set; }
    }
}
