//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMS.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/accommodationInfo/addaccommodationinfo.
        /// </summary>
        internal static string addAccommodationInfoPath {
            get {
                return ResourceManager.GetString("addAccommodationInfoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/authentication/addaccount.
        /// </summary>
        internal static string addAccountPath {
            get {
                return ResourceManager.GetString("addAccountPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/article/addarticle.
        /// </summary>
        internal static string addArticlePath {
            get {
                return ResourceManager.GetString("addArticlePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/author/addauthor.
        /// </summary>
        internal static string addAuthorPath {
            get {
                return ResourceManager.GetString("addAuthorPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/award/addaward.
        /// </summary>
        internal static string addAwardPath {
            get {
                return ResourceManager.GetString("addAwardPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/room/addbuilding.
        /// </summary>
        internal static string addBuildingPath {
            get {
                return ResourceManager.GetString("addBuildingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/conference/addconference.
        /// </summary>
        internal static string addConferencePath {
            get {
                return ResourceManager.GetString("addConferencePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/emergencyinfo/addemergencyinfo.
        /// </summary>
        internal static string addEmergencyInfoPath {
            get {
                return ResourceManager.GetString("addEmergencyInfoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/event/addevent.
        /// </summary>
        internal static string addEventPath {
            get {
                return ResourceManager.GetString("addEventPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/message/addmessage.
        /// </summary>
        internal static string addMessagePath {
            get {
                return ResourceManager.GetString("addMessagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/presentation/addpresentation.
        /// </summary>
        internal static string addPresentationPath {
            get {
                return ResourceManager.GetString("addPresentationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/review/addreview.
        /// </summary>
        internal static string addReviewPath {
            get {
                return ResourceManager.GetString("addReviewPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/authentication/addrole.
        /// </summary>
        internal static string addRolePath {
            get {
                return ResourceManager.GetString("addRolePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/room/addroom.
        /// </summary>
        internal static string addRoomPath {
            get {
                return ResourceManager.GetString("addRoomPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/session/addsession.
        /// </summary>
        internal static string addSessionPath {
            get {
                return ResourceManager.GetString("addSessionPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/session/addsespecialsession.
        /// </summary>
        internal static string addSpecialSessionPath {
            get {
                return ResourceManager.GetString("addSpecialSessionPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/submission/addsubmission.
        /// </summary>
        internal static string addSubmissionPath {
            get {
                return ResourceManager.GetString("addSubmissionPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/task/addtask.
        /// </summary>
        internal static string addTaskPath {
            get {
                return ResourceManager.GetString("addTaskPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/travelinfo/addtravel.
        /// </summary>
        internal static string addTravelPath {
            get {
                return ResourceManager.GetString("addTravelPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/welcomepackgift/addwelcomepackgift.
        /// </summary>
        internal static string addWelcomePackGiftPath {
            get {
                return ResourceManager.GetString("addWelcomePackGiftPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/welcomepack/addwelcomepack.
        /// </summary>
        internal static string addWelcomePackPath {
            get {
                return ResourceManager.GetString("addWelcomePackPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/welcomepackreceiver/addwelcomepackreceiver.
        /// </summary>
        internal static string addWelcomePackReceiverPath {
            get {
                return ResourceManager.GetString("addWelcomePackReceiverPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/authentication/changepassword.
        /// </summary>
        internal static string changePasswordPath {
            get {
                return ResourceManager.GetString("changePasswordPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/accommodationinfo/deleteaccommodationinfo.
        /// </summary>
        internal static string deleteAccommodationInfoPath {
            get {
                return ResourceManager.GetString("deleteAccommodationInfoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/authentication/deleteaccount.
        /// </summary>
        internal static string deleteAccountPath {
            get {
                return ResourceManager.GetString("deleteAccountPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/article/deletearticle.
        /// </summary>
        internal static string deleteArticlePath {
            get {
                return ResourceManager.GetString("deleteArticlePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/author/deleteauthor.
        /// </summary>
        internal static string deleteAuthorPath {
            get {
                return ResourceManager.GetString("deleteAuthorPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/award/deleteaward.
        /// </summary>
        internal static string deleteAwardPath {
            get {
                return ResourceManager.GetString("deleteAwardPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/room/deletebuildingforconference.
        /// </summary>
        internal static string deleteBuildingForConferencePath {
            get {
                return ResourceManager.GetString("deleteBuildingForConferencePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/room/deletebuilding.
        /// </summary>
        internal static string deleteBuildingPath {
            get {
                return ResourceManager.GetString("deleteBuildingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/conference/deleteconference.
        /// </summary>
        internal static string deleteConferencePath {
            get {
                return ResourceManager.GetString("deleteConferencePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/emergencyinfo/deletemergencyinfo.
        /// </summary>
        internal static string deleteEmergencyInfoPath {
            get {
                return ResourceManager.GetString("deleteEmergencyInfoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/event/deleteevent.
        /// </summary>
        internal static string deleteEventPath {
            get {
                return ResourceManager.GetString("deleteEventPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/message/deletemessage.
        /// </summary>
        internal static string deleteMessagePath {
            get {
                return ResourceManager.GetString("deleteMessagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/presentation/deletepresentation.
        /// </summary>
        internal static string deletePresentationPath {
            get {
                return ResourceManager.GetString("deletePresentationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/review/deletereview.
        /// </summary>
        internal static string deleteReviewPath {
            get {
                return ResourceManager.GetString("deleteReviewPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/authentication/deleteroleforconferenceandaccount.
        /// </summary>
        internal static string deleteRoleForConferenceAndAccountPath {
            get {
                return ResourceManager.GetString("deleteRoleForConferenceAndAccountPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/room/deleteroom.
        /// </summary>
        internal static string deleteRoomPath {
            get {
                return ResourceManager.GetString("deleteRoomPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/session/deletesession.
        /// </summary>
        internal static string deleteSessionPath {
            get {
                return ResourceManager.GetString("deleteSessionPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/session/deletespecialsession.
        /// </summary>
        internal static string deleteSpecialSessionPath {
            get {
                return ResourceManager.GetString("deleteSpecialSessionPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/submission/deletesubmission.
        /// </summary>
        internal static string deleteSubmissionPath {
            get {
                return ResourceManager.GetString("deleteSubmissionPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/task/deletetask.
        /// </summary>
        internal static string deleteTaskPath {
            get {
                return ResourceManager.GetString("deleteTaskPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/travelinfo/deletetravel.
        /// </summary>
        internal static string deleteTravelPath {
            get {
                return ResourceManager.GetString("deleteTravelPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/welcomepackgift/deletewelcomepackgift.
        /// </summary>
        internal static string deleteWelcomePackGiftPath {
            get {
                return ResourceManager.GetString("deleteWelcomePackGiftPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/welcomepack/deletewelcomepack.
        /// </summary>
        internal static string deleteWelcomePackPath {
            get {
                return ResourceManager.GetString("deleteWelcomePackPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/welcomepackreceiver/deletewelcomepackreceiver.
        /// </summary>
        internal static string deleteWelcomePackReceiverPath {
            get {
                return ResourceManager.GetString("deleteWelcomePackReceiverPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/accommodationinfo/editaccommodationinfo.
        /// </summary>
        internal static string editAccommodationInfoPath {
            get {
                return ResourceManager.GetString("editAccommodationInfoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/authentication/editaccount.
        /// </summary>
        internal static string editAccountPath {
            get {
                return ResourceManager.GetString("editAccountPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/article/editarticle.
        /// </summary>
        internal static string editArticlePath {
            get {
                return ResourceManager.GetString("editArticlePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/author/editauthor.
        /// </summary>
        internal static string editAuthorPath {
            get {
                return ResourceManager.GetString("editAuthorPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/award/editaward.
        /// </summary>
        internal static string editAwardPath {
            get {
                return ResourceManager.GetString("editAwardPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/room/editbuilding.
        /// </summary>
        internal static string editBuildingPath {
            get {
                return ResourceManager.GetString("editBuildingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/conference/editconference.
        /// </summary>
        internal static string editConferencePath {
            get {
                return ResourceManager.GetString("editConferencePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/emergencyinfo/editemergencyinfo.
        /// </summary>
        internal static string editEmergencyInfoPath {
            get {
                return ResourceManager.GetString("editEmergencyInfoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/event/editevent.
        /// </summary>
        internal static string editEventPath {
            get {
                return ResourceManager.GetString("editEventPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/message/editmessage.
        /// </summary>
        internal static string editMessagePath {
            get {
                return ResourceManager.GetString("editMessagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/presentation/editpresentation.
        /// </summary>
        internal static string editPresentationPath {
            get {
                return ResourceManager.GetString("editPresentationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/review/editreview.
        /// </summary>
        internal static string editReviewPath {
            get {
                return ResourceManager.GetString("editReviewPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/room/editroom.
        /// </summary>
        internal static string editRoomPath {
            get {
                return ResourceManager.GetString("editRoomPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/session/editsession.
        /// </summary>
        internal static string editSessionPath {
            get {
                return ResourceManager.GetString("editSessionPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/session/editspecialsession.
        /// </summary>
        internal static string editSpecialSessionPath {
            get {
                return ResourceManager.GetString("editSpecialSessionPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/submission/editsubmission.
        /// </summary>
        internal static string editSubmissionPath {
            get {
                return ResourceManager.GetString("editSubmissionPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/task/edittask.
        /// </summary>
        internal static string editTaskPath {
            get {
                return ResourceManager.GetString("editTaskPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/travelinfo/edittravel.
        /// </summary>
        internal static string editTravelPath {
            get {
                return ResourceManager.GetString("editTravelPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/welcomepackgift/editwelcomepackgift.
        /// </summary>
        internal static string editWelcomePackGiftPath {
            get {
                return ResourceManager.GetString("editWelcomePackGiftPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/welcomepack/editwelcomepack.
        /// </summary>
        internal static string editWelcomePackPath {
            get {
                return ResourceManager.GetString("editWelcomePackPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/welcomepackreceiver/editwelcomepackreceiver.
        /// </summary>
        internal static string editWelcomePackReceiverPath {
            get {
                return ResourceManager.GetString("editWelcomePackReceiverPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/accommodationinfo/accommodationinfobyid.
        /// </summary>
        internal static string getAccommodationInfoByIdPath {
            get {
                return ResourceManager.GetString("getAccommodationInfoByIdPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/accommodationinfo/accommodationinfoinfo.
        /// </summary>
        internal static string getAccommodationInfoInfoPath {
            get {
                return ResourceManager.GetString("getAccommodationInfoInfoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/authentication/accountbyid.
        /// </summary>
        internal static string getAccountByIdPath {
            get {
                return ResourceManager.GetString("getAccountByIdPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/authentication/accountbylogin.
        /// </summary>
        internal static string getAccountByLoginPath {
            get {
                return ResourceManager.GetString("getAccountByLoginPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/authentication/accountsforrole.
        /// </summary>
        internal static string getAccountsForRolePath {
            get {
                return ResourceManager.GetString("getAccountsForRolePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/article/articlebyid.
        /// </summary>
        internal static string getArticleByIdPath {
            get {
                return ResourceManager.GetString("getArticleByIdPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/article/articles.
        /// </summary>
        internal static string getArticlesPath {
            get {
                return ResourceManager.GetString("getArticlesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/author/authorbyid.
        /// </summary>
        internal static string getAuthorByIdPath {
            get {
                return ResourceManager.GetString("getAuthorByIdPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/author/authors.
        /// </summary>
        internal static string getAuthorsPath {
            get {
                return ResourceManager.GetString("getAuthorsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/award/awardbyid.
        /// </summary>
        internal static string getAwardByIdPath {
            get {
                return ResourceManager.GetString("getAwardByIdPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/award/awards.
        /// </summary>
        internal static string getAwardsPath {
            get {
                return ResourceManager.GetString("getAwardsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/conference/conferencebyid.
        /// </summary>
        internal static string getConferenceByIdPath {
            get {
                return ResourceManager.GetString("getConferenceByIdPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/conference/program.
        /// </summary>
        internal static string getConferenceProgram {
            get {
                return ResourceManager.GetString("getConferenceProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/authentication/conferencesforaccount.
        /// </summary>
        internal static string getConferencesForAccountPath {
            get {
                return ResourceManager.GetString("getConferencesForAccountPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/conference/conferences.
        /// </summary>
        internal static string getConferencesPath {
            get {
                return ResourceManager.GetString("getConferencesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/emergencyinfo/emergencyinfobyid.
        /// </summary>
        internal static string getEmergencyInfoByIdPath {
            get {
                return ResourceManager.GetString("getEmergencyInfoByIdPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/emergencyinfo/emergencyinfoinfo.
        /// </summary>
        internal static string getEmergencyInfoInfoPath {
            get {
                return ResourceManager.GetString("getEmergencyInfoInfoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/event/eventbyid.
        /// </summary>
        internal static string getEventByIdPath {
            get {
                return ResourceManager.GetString("getEventByIdPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/event/events.
        /// </summary>
        internal static string getEventsPath {
            get {
                return ResourceManager.GetString("getEventsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/authentication/hrroles.
        /// </summary>
        internal static string getHRRolesPath {
            get {
                return ResourceManager.GetString("getHRRolesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to null.
        /// </summary>
        internal static string getListRoomsPath {
            get {
                return ResourceManager.GetString("getListRoomsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/review/reviewbyid.
        /// </summary>
        internal static string getReviewByIdPath {
            get {
                return ResourceManager.GetString("getReviewByIdPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/review/reviews.
        /// </summary>
        internal static string getReviewInfoPath {
            get {
                return ResourceManager.GetString("getReviewInfoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/authentication/rolename.
        /// </summary>
        internal static string getRoleNamePath {
            get {
                return ResourceManager.GetString("getRoleNamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/authentication/rolesforconferenceandaccount.
        /// </summary>
        internal static string getRolesForConferenceAndAccountPath {
            get {
                return ResourceManager.GetString("getRolesForConferenceAndAccountPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/authentication/roles.
        /// </summary>
        internal static string getRolesPath {
            get {
                return ResourceManager.GetString("getRolesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/submission/submissionbyid.
        /// </summary>
        internal static string getSubmissionByIdPath {
            get {
                return ResourceManager.GetString("getSubmissionByIdPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/submission/submissions.
        /// </summary>
        internal static string getSubmissionsPath {
            get {
                return ResourceManager.GetString("getSubmissionsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/task/taskbyid.
        /// </summary>
        internal static string getTaskByIdPath {
            get {
                return ResourceManager.GetString("getTaskByIdPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/task/tasksforemployee.
        /// </summary>
        internal static string getTasksForEmployeePath {
            get {
                return ResourceManager.GetString("getTasksForEmployeePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/task/tasks.
        /// </summary>
        internal static string getTasksPath {
            get {
                return ResourceManager.GetString("getTasksPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/travelinfo/travelbyid.
        /// </summary>
        internal static string getTravelByIdPath {
            get {
                return ResourceManager.GetString("getTravelByIdPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/travelinfo/travelinfo.
        /// </summary>
        internal static string getTravelInfoPath {
            get {
                return ResourceManager.GetString("getTravelInfoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/welcomepack/welcomepackbyid.
        /// </summary>
        internal static string getWelcomePackByIdPath {
            get {
                return ResourceManager.GetString("getWelcomePackByIdPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/welcomepackgift/welcomepackgiftbyid.
        /// </summary>
        internal static string getWelcomePackGiftByIdPath {
            get {
                return ResourceManager.GetString("getWelcomePackGiftByIdPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/welcomepackgift/welcomepackgiftinfo.
        /// </summary>
        internal static string getWelcomePackGiftInfoPath {
            get {
                return ResourceManager.GetString("getWelcomePackGiftInfoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/welcomepack/welcomepackinfo.
        /// </summary>
        internal static string getWelcomePackInfoPath {
            get {
                return ResourceManager.GetString("getWelcomePackInfoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/welcomepackreceiver/welcomepackreceiverbyid.
        /// </summary>
        internal static string getWelcomePackReceiverByIdPath {
            get {
                return ResourceManager.GetString("getWelcomePackReceiverByIdPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/welcomepackreceiver/welcomepackreceiverinfo.
        /// </summary>
        internal static string getWelcomePackReceiverInfoPath {
            get {
                return ResourceManager.GetString("getWelcomePackReceiverInfoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/authentication/login.
        /// </summary>
        internal static string loginPath {
            get {
                return ResourceManager.GetString("loginPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/room/setbuildingforconference.
        /// </summary>
        internal static string setBuildingForConferencePath {
            get {
                return ResourceManager.GetString("setBuildingForConferencePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/authentication/setroleforconferenceandaccount.
        /// </summary>
        internal static string setRoleForConferenceAndAccountPath {
            get {
                return ResourceManager.GetString("setRoleForConferenceAndAccountPath", resourceCulture);
            }
        }
    }
}
