//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMS.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/authentication/accountbylogin.
        /// </summary>
        internal static string accountByLoginPath {
            get {
                return ResourceManager.GetString("accountByLoginPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/authentication/addaccount.
        /// </summary>
        internal static string addAccountPath {
            get {
                return ResourceManager.GetString("addAccountPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/conference/addconference.
        /// </summary>
        internal static string addConferencePath {
            get {
                return ResourceManager.GetString("addConferencePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/authentication/addrole.
        /// </summary>
        internal static string addRolePath {
            get {
                return ResourceManager.GetString("addRolePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/authentication/changepassword.
        /// </summary>
        internal static string changePasswordPath {
            get {
                return ResourceManager.GetString("changePasswordPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/authentication/conferencesforaccount.
        /// </summary>
        internal static string conferencesForAccountPath {
            get {
                return ResourceManager.GetString("conferencesForAccountPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/conference/conferences.
        /// </summary>
        internal static string conferencesPath {
            get {
                return ResourceManager.GetString("conferencesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/authentication/login.
        /// </summary>
        internal static string loginPath {
            get {
                return ResourceManager.GetString("loginPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/authentication/rolename.
        /// </summary>
        internal static string roleNamePath {
            get {
                return ResourceManager.GetString("roleNamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/authentication/rolesforconferenceandaccount.
        /// </summary>
        internal static string rolesForConferenceAndAccountPath {
            get {
                return ResourceManager.GetString("rolesForConferenceAndAccountPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/authentication/roles.
        /// </summary>
        internal static string rolesPath {
            get {
                return ResourceManager.GetString("rolesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/authentication/setroleforconferenceandaccount.
        /// </summary>
        internal static string setRoleForConferenceAndAccountPath {
            get {
                return ResourceManager.GetString("setRoleForConferenceAndAccountPath", resourceCulture);
            }
        }
    }
}
