//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMS.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/authentication/addaccount.
        /// </summary>
        internal static string addAccountPath {
            get {
                return ResourceManager.GetString("addAccountPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/award/addaward.
        /// </summary>
        internal static string addAwardPath {
            get {
                return ResourceManager.GetString("addAwardPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/room/addbuilding.
        /// </summary>
        internal static string addBuildingPath {
            get {
                return ResourceManager.GetString("addBuildingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/conference/addconference.
        /// </summary>
        internal static string addConferencePath {
            get {
                return ResourceManager.GetString("addConferencePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/event/addevent.
        /// </summary>
        internal static string addEventPath {
            get {
                return ResourceManager.GetString("addEventPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/message/addmessage.
        /// </summary>
        internal static string addMessagePath {
            get {
                return ResourceManager.GetString("addMessagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/presentation/addpresentation.
        /// </summary>
        internal static string addPresentationPath {
            get {
                return ResourceManager.GetString("addPresentationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/authentication/addrole.
        /// </summary>
        internal static string addRolePath {
            get {
                return ResourceManager.GetString("addRolePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/room/addroom.
        /// </summary>
        internal static string addRoomPath {
            get {
                return ResourceManager.GetString("addRoomPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/session/addsession.
        /// </summary>
        internal static string addSessionPath {
            get {
                return ResourceManager.GetString("addSessionPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/session/addsespecialsession.
        /// </summary>
        internal static string addSpecialSessionPath {
            get {
                return ResourceManager.GetString("addSpecialSessionPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/task/addtask.
        /// </summary>
        internal static string addTaskPath {
            get {
                return ResourceManager.GetString("addTaskPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/authentication/changepassword.
        /// </summary>
        internal static string changePasswordPath {
            get {
                return ResourceManager.GetString("changePasswordPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/authentication/deleteaccount.
        /// </summary>
        internal static string deleteAccountPath {
            get {
                return ResourceManager.GetString("deleteAccountPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/award/deleteaward.
        /// </summary>
        internal static string deleteAwardPath {
            get {
                return ResourceManager.GetString("deleteAwardPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/room/deletebuildingforconference.
        /// </summary>
        internal static string deleteBuildingForConferencePath {
            get {
                return ResourceManager.GetString("deleteBuildingForConferencePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/room/deletebuilding.
        /// </summary>
        internal static string deleteBuildingPath {
            get {
                return ResourceManager.GetString("deleteBuildingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/conference/deleteconference.
        /// </summary>
        internal static string deleteConferencePath {
            get {
                return ResourceManager.GetString("deleteConferencePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/event/deleteevent.
        /// </summary>
        internal static string deleteEventPath {
            get {
                return ResourceManager.GetString("deleteEventPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/message/deletemessage.
        /// </summary>
        internal static string deleteMessagePath {
            get {
                return ResourceManager.GetString("deleteMessagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/presentation/deletepresentation.
        /// </summary>
        internal static string deletePresentationPath {
            get {
                return ResourceManager.GetString("deletePresentationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/authentication/deleteroleforconferenceandaccount.
        /// </summary>
        internal static string deleteRoleForConferenceAndAccountPath {
            get {
                return ResourceManager.GetString("deleteRoleForConferenceAndAccountPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/room/deleteroom.
        /// </summary>
        internal static string deleteRoomPath {
            get {
                return ResourceManager.GetString("deleteRoomPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/session/deletesession.
        /// </summary>
        internal static string deleteSessionPath {
            get {
                return ResourceManager.GetString("deleteSessionPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/session/deletespecialsession.
        /// </summary>
        internal static string deleteSpecialSessionPath {
            get {
                return ResourceManager.GetString("deleteSpecialSessionPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/task/deletetask.
        /// </summary>
        internal static string deleteTaskPath {
            get {
                return ResourceManager.GetString("deleteTaskPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/authentication/editaccount.
        /// </summary>
        internal static string editAccountPath {
            get {
                return ResourceManager.GetString("editAccountPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/award/editaward.
        /// </summary>
        internal static string editAwardPath {
            get {
                return ResourceManager.GetString("editAwardPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/room/editbuilding.
        /// </summary>
        internal static string editBuildingPath {
            get {
                return ResourceManager.GetString("editBuildingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/conference/editconference.
        /// </summary>
        internal static string editConferencePath {
            get {
                return ResourceManager.GetString("editConferencePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/event/editevent.
        /// </summary>
        internal static string editEventPath {
            get {
                return ResourceManager.GetString("editEventPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/message/editmessage.
        /// </summary>
        internal static string editMessagePath {
            get {
                return ResourceManager.GetString("editMessagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/presentation/editpresentation.
        /// </summary>
        internal static string editPresentationPath {
            get {
                return ResourceManager.GetString("editPresentationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/room/editroom.
        /// </summary>
        internal static string editRoomPath {
            get {
                return ResourceManager.GetString("editRoomPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/session/editsession.
        /// </summary>
        internal static string editSessionPath {
            get {
                return ResourceManager.GetString("editSessionPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/session/editspecialsession.
        /// </summary>
        internal static string editSpecialSessionPath {
            get {
                return ResourceManager.GetString("editSpecialSessionPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/task/edittask.
        /// </summary>
        internal static string editTaskPath {
            get {
                return ResourceManager.GetString("editTaskPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/authentication/accountbyid.
        /// </summary>
        internal static string getAccountByIdPath {
            get {
                return ResourceManager.GetString("getAccountByIdPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/authentication/accountbylogin.
        /// </summary>
        internal static string getAccountByLoginPath {
            get {
                return ResourceManager.GetString("getAccountByLoginPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/authentication/accountsforrole.
        /// </summary>
        internal static string getAccountsForRolePath {
            get {
                return ResourceManager.GetString("getAccountsForRolePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/award/awardbyid.
        /// </summary>
        internal static string getAwardByIdPath {
            get {
                return ResourceManager.GetString("getAwardByIdPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/award/awards.
        /// </summary>
        internal static string getAwardsPath {
            get {
                return ResourceManager.GetString("getAwardsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/conference/conferencebyid.
        /// </summary>
        internal static string getConferenceByIdPath {
            get {
                return ResourceManager.GetString("getConferenceByIdPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/authentication/conferencesforaccount.
        /// </summary>
        internal static string getConferencesForAccountPath {
            get {
                return ResourceManager.GetString("getConferencesForAccountPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/conference/conferences.
        /// </summary>
        internal static string getConferencesPath {
            get {
                return ResourceManager.GetString("getConferencesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/event/eventbyid.
        /// </summary>
        internal static string getEventByIdPath {
            get {
                return ResourceManager.GetString("getEventByIdPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/event/events.
        /// </summary>
        internal static string getEventsPath {
            get {
                return ResourceManager.GetString("getEventsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/authentication/hrroles.
        /// </summary>
        internal static string getHRRolesPath {
            get {
                return ResourceManager.GetString("getHRRolesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/event/listrooms.
        /// </summary>
        internal static string getListRoomsPath {
            get {
                return ResourceManager.GetString("getListRoomsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/authentication/rolename.
        /// </summary>
        internal static string getRoleNamePath {
            get {
                return ResourceManager.GetString("getRoleNamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/authentication/rolesforconferenceandaccount.
        /// </summary>
        internal static string getRolesForConferenceAndAccountPath {
            get {
                return ResourceManager.GetString("getRolesForConferenceAndAccountPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/authentication/roles.
        /// </summary>
        internal static string getRolesPath {
            get {
                return ResourceManager.GetString("getRolesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/task/taskbyid.
        /// </summary>
        internal static string getTaskByIdPath {
            get {
                return ResourceManager.GetString("getTaskByIdPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/task/tasksforemployee.
        /// </summary>
        internal static string getTasksForEmployeePath {
            get {
                return ResourceManager.GetString("getTasksForEmployeePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/task/tasks.
        /// </summary>
        internal static string getTasksPath {
            get {
                return ResourceManager.GetString("getTasksPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/authentication/login.
        /// </summary>
        internal static string loginPath {
            get {
                return ResourceManager.GetString("loginPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/room/setbuildingforconference.
        /// </summary>
        internal static string setBuildingForConferencePath {
            get {
                return ResourceManager.GetString("setBuildingForConferencePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на api/authentication/setroleforconferenceandaccount.
        /// </summary>
        internal static string setRoleForConferenceAndAccountPath {
            get {
                return ResourceManager.GetString("setRoleForConferenceAndAccountPath", resourceCulture);
            }
        }
    }
}
